version: "3.4"

# Lanch local dev environement
# Make sure to add .env file in the same directory,
# containing :
# WEB_SERVER_PORT

services:
  web:
    image: node:18.4.0
    container_name: web
    working_dir: /home/coverify
    tty: true
    env_file:
      - ./packages/app/web/.env.example
    environment:
      - VITE_SERVER_PORT=$WEB_SERVER_PORT
    command: >
      sh -c "yarn install
      && cd packages/app/web
      && yarn dev"
    ports:
      - "$WEB_SERVER_PORT:$WEB_SERVER_PORT"
    volumes:
      # Speed up install process
      - .:/home/coverify
      # bind volumes
      - common-node-modules:/home/job4/node_modules
      - web-node-modules:/home/job4/packages/app/web/node_modules

volumes:
  # Creates a coverify-node-modules docker volume.
  # Clear the volume with `docker volume prune`
  # This volume can be bound within containers, and will be populated
  # by 'yarn install' command within a container.
  common-node-modules:
  web-node-modules:
